import { escapeHtml as e } from "./formatting.js";
import { WORKBOOK_IDENTITY_LABELS, WORKBOOK_IDENTITY_LIMITS } from "./workbook-data.js";

export const workbookStatusText = model => ({ loading: "正在讀取手冊…", saving: "正在保存…", saved: "已保存至此裝置", error: model.error || "未能保存，輸入仍保留。", conflict: model.error || "另一分頁已修改手冊，已暫停保存。" }[model.status]);
const paragraphs = lines => (lines || []).map(line => `<p>${e(line)}</p>`).join("");
export function renderWorkbook(model) {
  const disabled = model.status === "loading" || !model.initialized || model.busy;
  const section = model.part;
  const field = item => `<div class="workbook-field"><label for="wb-${e(item.id)}">${e(item.label)}</label><textarea id="wb-${e(item.id)}" data-workbook-field="${e(item.id)}" maxlength="10000" rows="${item.id === "essay-body" ? 12 : 4}" ${disabled ? "disabled" : ""}>${e(model.answers[item.id])}</textarea><small id="wb-count-${e(item.id)}">${Array.from(model.answers[item.id]).length} 字${item.id === "essay-body" ? "；目標約 600 字，字數不限制下載。" : "；最多 10,000 字元。"}</small></div>`;
  const selected = model.selectedPhotos.map(photo => `<figure>${photo.url ? `<img src="${e(photo.url)}" alt="${e(photo.title)}文章配圖" width="${photo.width}" height="${photo.height}" />` : `<p>${e(photo.title)}：${e(photo.reason || "未能顯示預覽")}</p>`}<figcaption>${e(photo.title)}<button type="button" class="button button-secondary" data-workbook-remove-photo="${e(photo.photoId)}" ${disabled ? "disabled" : ""}>移除此配圖</button></figcaption></figure>`).join("");
  const photos = section?.id === "essay" ? `<section class="workbook-photos" aria-labelledby="workbook-photo-title"><h2 id="workbook-photo-title">文章配圖（${model.selectedPhotos.length}／6）</h2><p>從旅途回憶選取最多六張，相片會完整保留比例。</p><div class="workbook-selected-photos">${selected}</div><button id="wb-picker-open" type="button" class="button button-secondary" data-workbook-picker ${disabled || model.busy ? "disabled" : ""}>${model.pickerOpen ? "收起選圖" : "選取文章配圖"}</button>${model.pickerOpen ? `<div id="wb-picker"><p role="status">${model.photoReadState === "loading" ? "正在讀取相片，暫時不能核對配圖。" : model.photoReadState === "error" ? "相片讀取失敗，暫時不能核對配圖；請重試。" : model.photoCount ? `共有 ${model.photoCount} 張紀念照` : "還沒有紀念照。請先到景點打卡後拍照。"}</p>${model.photoReadState === "error" ? '<button class="button button-secondary" data-workbook-photos-retry>重試讀取相片</button>' : ""}<div class="workbook-photo-grid">${model.pickerPhotos.map(photo => `<label><img src="${e(photo.url || "")}" alt="${e(photo.title)}" width="${photo.width}" height="${photo.height}" /><span><input type="checkbox" data-workbook-photo="${e(photo.photoId)}" ${photo.selected ? "checked" : ""} ${!photo.selected && model.selectedPhotos.length >= 6 ? "disabled" : ""} />${e(photo.title)}</span></label>`).join("")}</div>${model.photoReadState === "ready" && model.photoCount ? `<div class="workbook-pagination"><button class="button button-secondary" data-workbook-photo-page="${model.photoPage - 1}" ${model.photoPage === 0 ? "disabled" : ""}>上一頁</button><span>第 ${model.photoPage + 1}／${model.photoPages} 頁</span><button class="button button-secondary" data-workbook-photo-page="${model.photoPage + 1}" ${model.photoPage + 1 >= model.photoPages ? "disabled" : ""}>下一頁</button></div>` : ""}</div>` : ""}</section>` : "";
  const ratings = section?.id === "reflection" ? `<section><h2>${e(model.ratingInstruction)}</h2>${model.ratingFields.map(item => `<fieldset class="workbook-rating"><legend>${e(item.label)}</legend><div>${[1, 2, 3, 4, 5].map(score => `<label><input type="radio" name="${e(item.id)}" data-workbook-rating="${e(item.id)}" value="${score}" ${model.ratings[item.id] === score ? "checked" : ""} ${disabled ? "disabled" : ""} />${score}</label>`).join("")}<button type="button" class="button-text" data-workbook-clear-rating="${e(item.id)}" ${disabled ? "disabled" : ""}>清除評分</button></div></fieldset>`).join("")}</section>` : "";
  const works = section?.id === "works" ? `<div class="workbook-instructions"><h2>活動花絮短片</h2>${paragraphs(model.works.video)}<h2>AI 融合圖片</h2>${paragraphs(model.works.ai)}<a class="button button-secondary" href="#memories">前往旅途回憶準備 AI 素材包</a><h2>作品上傳</h2><p>${e(model.works.upload)}</p><a href="${e(model.works.uploadUrl)}" target="_blank" rel="noopener noreferrer">${e(model.works.uploadUrl)} ↗</a><p>短片剪輯及 AI 圖片生成由你在外部工具完成，上傳也由你自行操作。此頁不會顯示「已提交」。上傳頁只用於短片與 AI 圖片；文字課業 PDF 用於保存及列印。</p></div>` : "";
  const overview = !section ? `<div class="workbook-directory">${model.progress.map(part => `<a href="#workbook/${part.id}" class="workbook-part"><strong>${e(part.title)}</strong><span>${part.total ? `已填 ${part.filled}／${part.total} 欄` : "查看製作與上傳指引"}</span></a>`).join("")}</div><p>進度只表示欄位是否已填，不評判答案質素或校方是否接受作品。未完成打卡也可以開始填寫。</p>` : `${paragraphs(section.instructions)}${section.fields.map(field).join("")}${photos}${ratings}${works}`;
  const exportPanel = model.exportOpen ? `<section class="workbook-export" aria-labelledby="workbook-export-title"><h2 id="workbook-export-title" tabindex="-1">下載學習手冊 PDF</h2><p>姓名、班別及學號必填，只留在目前手冊和輸出 PDF；離開手冊或重載後清除，不加入草稿、備份或檔名。</p><div class="workbook-identity">${Object.entries(WORKBOOK_IDENTITY_LIMITS).map(([key, max]) => `<label for="wb-id-${key}">${WORKBOOK_IDENTITY_LABELS[key]}（必填）<input id="wb-id-${key}" data-workbook-identity="${key}" value="${e(model.identity[key])}" maxlength="${max * 2}" required autocomplete="off" ${model.busy ? "disabled" : ""}/><small id="wb-id-count-${key}">${Array.from(model.identity[key]).length}／${max} 字</small></label>`).join("")}</div><details ${model.missing.length ? "" : "hidden"}><summary>尚未填寫 ${model.missing.length} 項（可下載草稿 PDF）</summary><ul>${model.missing.map(label => `<li>${e(label)}</li>`).join("")}</ul></details><p id="workbook-pdf-status" role="status">${e(model.pdfMessage || "空項會標示「尚未填寫」。下載後請自行保存 PDF。")}</p><div class="workbook-toolbar"><button id="wb-pdf-download" class="button button-primary" data-workbook-pdf ${model.busy || disabled || model.status !== "saved" ? "disabled" : ""}>生成並下載 PDF</button><button class="button button-secondary" data-workbook-export-close>${model.busy ? "取消生成" : "收起下載"}</button></div></section>` : "";
  return `<div class="page-shell workbook-page">${section ? '<a class="back-link" href="#workbook">← 返回手冊目錄</a>' : ""}<p class="eyebrow">本機離線課業</p><h1>${section ? e(section.title) : "學習手冊"}</h1><div class="workbook-status"><p id="workbook-save-status" role="status">${e(workbookStatusText(model))}</p><button class="button button-secondary" data-workbook-retry ${model.status !== "error" ? "hidden" : ""}>重試保存</button><div id="workbook-conflict" ${model.status !== "conflict" ? "hidden" : ""}><p>先備份目前內容，再載入另一分頁版本；載入會取代此分頁的草稿。</p><button class="button button-secondary" data-workbook-backup>備份目前內容</button><button class="button button-secondary" data-workbook-load-latest ${model.backedUp ? "" : "disabled"}>載入另一分頁版本</button></div></div>${overview}<div class="workbook-toolbar"><button class="button button-primary" data-workbook-export-open ${disabled ? "disabled" : ""}>下載手冊 PDF</button><button class="button button-secondary" data-workbook-backup ${model.status === "loading" ? "disabled" : ""}>下載 JSON 備份</button><label class="button button-secondary workbook-restore-label" for="wb-restore">還原 JSON 備份</label><input id="wb-restore" type="file" accept="application/json,.json" data-workbook-restore ${disabled || model.busy || model.status === "conflict" ? "disabled" : ""}/></div>${exportPanel}<p class="privacy-note">草稿只存於此裝置，App 沒有額外加密。同源分頁共用儲存。PDF 和備份須由你自行保存；備份不含姓名、班別、學號、相片或打卡資料，還原後須重新選圖。清除本機旅程資料會一併清除手冊，但不會刪除已下載的檔案。</p></div>`;
}
